"""Merge Wikipedia and news corpus counts into the live engine data.

Usage:  python scripts/merge_corpora.py

Reads data_raw/wiki_unigrams.tsv (+ news_unigrams/news_bigrams if present),
then regenerates dhivehi_spell/data/corpus.tsv and data/bigrams.dat with
combined counts. Run build_corpus.py / build_news_corpus.py first.
"""

from __future__ import annotations

import os
import sys
from collections import Counter

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from dhivehi_spell.checker import SpellChecker  # noqa: E402
from dhivehi_spell.dictionary import Lexicon    # noqa: E402
from dhivehi_spell.thaana import parse_units    # noqa: E402

HERE = os.path.dirname(__file__)
RAW = os.path.join(HERE, "..", "data_raw")
DATA = os.path.join(HERE, "..", "dhivehi_spell", "data")

MIN_COUNT, MIN_BIGRAM, MAX_FREQ = 3, 3, 100000


def read_counts(path, cols):
    out = Counter()
    if os.path.exists(path):
        with open(path, encoding="utf-8-sig") as fh:
            for line in fh:
                parts = line.rstrip("\n").split("\t")
                if len(parts) == cols and not line.startswith("#"):
                    key = parts[0] if cols == 2 else (parts[0], parts[1])
                    out[key] += int(parts[-1])
    return out


def main() -> None:
    unigrams = read_counts(os.path.join(RAW, "wiki_unigrams.tsv"), 2)
    unigrams.update(read_counts(os.path.join(RAW, "news_unigrams.tsv"), 2))

    bigrams = read_counts(os.path.join(DATA, "bigrams.dat"), 3)
    bigrams.update(read_counts(os.path.join(RAW, "news_bigrams.tsv"), 3))

    # base lexicon WITHOUT the old corpus file, to decide what's new
    base = Lexicon()
    for name in ("wordlist.tsv", "radheef.tsv"):
        base.load(os.path.join(DATA, name))

    added = 0
    with open(os.path.join(DATA, "corpus.tsv"), "w", encoding="utf-8") as fh:
        fh.write("# Generated by scripts/merge_corpora.py from Wikipedia + "
                 "news corpora — do not edit by hand.\n")
        for word, count in unigrams.most_common():
            if count < MIN_COUNT or len(word) < 2 or word in base:
                continue
            if parse_units(word)[1]:
                continue
            fh.write("%s\t%d\n" % (word, min(count, MAX_FREQ)))
            added += 1

    kept = 0
    with open(os.path.join(DATA, "bigrams.dat"), "w", encoding="utf-8") as fh:
        fh.write("# w1 <TAB> w2 <TAB> count — merged corpora.\n")
        for (a, b), c in bigrams.most_common():
            if c < MIN_BIGRAM:
                break
            fh.write("%s\t%s\t%d\n" % (a, b, c))
            kept += 1

    print("corpus words: %d, bigrams: %d" % (added, kept))
    print("new total lexicon: %d" % len(SpellChecker().lexicon))


if __name__ == "__main__":
    main()
